name: Build and Distribute APK
    
on:
    push:
      branches:
      - develop

jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate Debug APK
        run: ./gradlew assembleDebug

      - name: Change wrapper permissions 
        run: chmod +x gradlew

  deploy:
    runs-on: ubuntu-latest
    needs: build_apk_aab
    steps:
      - name: Upload APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: app/build/outputs/apk/debug/app-debug.apk
